name: Send email
on: push
jobs:
  sendGrid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SendGrid
        uses: ./
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}